apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: security-case01
  name: security-case01
spec:
  containers:
  - image: bash
    command: ['sh', '-c',' curl http://security-case01/auth?token=123345690']
    name: security-case01
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: security-case01
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: security-case01
status:
  loadBalancer: {}