apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  annotations:
    container.seccomp.security.alpha.kubernetes.io/pod: runtime/default
    container.apparmor.security.beta.kubernetes.io/nginx: localhost/docker-default
  labels:
    run: nginx
  name: nginx
spec:
  automountServiceAccountToken: false
  serviceAccountName: default
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: 100
        cpu: 100
      limits:
        memory: 50
        cpu: 50
    securityContext:
      seccompProfile:
        type: RuntimeDefault
      runAsNonRoot: true
      runAsUser: 10001
      runAsGroup: 10001
      readOnlyRootFilesystem: true
      capabilities:
        drop: [all]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
