apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-05-20T16:55:10Z"
  labels:
    kubernetes.io/metadata.name: seminar
  name: seminar
  resourceVersion: "24934"
  uid: 6f2f3306-5433-4a78-bd02-ed0480e72358
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2025-05-20T17:02:15Z"
  name: seminar-sa
  namespace: seminar
  resourceVersion: "25281"
  uid: 639041ea-85af-49f3-a8e2-42a8a98ecb28
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2025-05-20T16:57:34Z"
  name: k8s-seminar
  namespace: seminar
  resourceVersion: "25053"
  uid: 3914e5a8-a1d5-490d-bc62-d55cf9c810bd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2025-05-20T16:58:59Z"
  name: k8s-seminar-bind
  namespace: seminar
  resourceVersion: "25123"
  uid: 20e485d2-49aa-4a55-802f-a1ea344c6eb1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-seminar
subjects:
- kind: ServiceAccount
  name: seminar-sa
  namespace: seminar